---
title: "R Notebook"
output: html_notebook
---
 

```{r}
library(Rcpp)
library(igraph)
library(Matrix)
update.packages("Rcpp")
setwd("C:/Users/bbessell/Projects/GitHub/AluNet")
Sys.setenv(PKG_CXXFLAGS = "-std=c++17")
Sys.which("make")
Sys.which("g++")
```

```{r}
Sys.getenv()
```

```{r}
sourceCpp("rcpp/compile_test.cpp", verbose = TRUE, rebuild = TRUE)
```

```{r}
sourceCpp("rcpp/GraphUtils.cpp", verbose = F, rebuild = TRUE)
```

```{r}
# test Rcpp graph construction with random graph (seg fault stress test)
source("r/createRandomZeroInflatedAdjacencyMatrix.R")
num_vertices <- 10
zero_prob <- 0.3
adjacency_matrix <- createRandomZeroInflatedAdjacencyMatrix(num_vertices, zero_prob)
#print(adjacency_matrix)
graph_data <- createGraphFromMatrix(adjacency_matrix)
edges <- graph_data$edges
weights <- graph_data$weights
#print(graph_data)
g <- graph.data.frame(graph_data)
#print(g)
edge_weights <- E(g)$weight
#print(edge_weights)
#plot(g)
#l <- layout_on_sphere(g)
plot(g)
```

eight
#print(edge_weights)

```{r}
g_fromList <- createGraphFromList(graph_data)
```

```{r}
test_graph_input <- list(
  from=c("A","B", "C"),
  to=c("B", "C", "D"),
  weight=c(10, 20, 30)
)
test_graph_output <- createGraphFromList(test_graph_input)
print(test_graph_input)
print(test_graph_output)
```


```{r}
source("r/graphFromFitHIC.R")
g_list <- graphFromFitHIC("data/GSE148434_NS_all.5kb.1e-2.FitHiC.all.txt", "chr1")
graph_data <- createGraphFromList(g_list)
edges <- g_list$edges
weights <- g_list$weights
#print(graph_data)
g <- graph.data.frame(graph_data)
#print(g)
edge_weights <- E(g)$w
#plot(g)
plot.igraph(g)
```
