# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

createGraphFromList <- function(graphList) {
    .Call(`_AluNet_createGraphFromList`, graphList)
}

#' Takes an R List, converts it to a Graph object, and runs the Leiden algorithm
#' @param graphList R List containing the graph
#' @param iterations number of iterations to run the Leiden algorithm
#' @param gamma resolution parameter
#' @param theta temperature parameter
#' @return Rcpp::List : R List containing the graph, community assignments, and quality
#' @example runLeiden(graphList, 10, 0.1, 0.01)
#' @export
runLeiden <- function(graphList, iterations, gamma, theta, seed = 0L) {
    .Call(`_AluNet_runLeiden`, graphList, iterations, gamma, theta, seed)
}

